### ISSUE TITLE
Certificates issued by Digicert GeoTrust Cloud DV are not trusted

### ISSUE THREAD

**Issue by ciorisgithub** [ipxe/ipxe#1107]
Digicert uses GeoTrust TLS RSA CA G1 as intermediate certificate and DigiCert Global Root G2 as root certificate. Can those be added to the https://ca.ipxe.org/? Adding those manually using TRUST=... and CERT=... works as expected, but it would be good to be added so they are automatically trusted.

Thanks

**Comment by NiKiZe** [comment]
iPXE CA is based on Mozilla, are they missing there?

**Comment by ciorisgithub** [comment]
I couldn't find them in there.... unless I'm missing something...

**Comment by Paper-Dragon** [comment]
issue by https://letsencrypt.org/zh-cn/certificates/ also it,sometime can use, 
here https://github.com/ipxe/ipxe/discussions/1105

**Comment by Paper-Dragon** [comment]
> issue by https://letsencrypt.org/zh-cn/certificates/ also it,sometime can use, here #1105

![图片](https://github.com/ipxe/ipxe/assets/49874457/4f64da68-f382-4f0f-acad-b59f7280fbf7)

**Comment by NiKiZe** [comment]
I can't read that... This is not an issue for many others, are you sure this isn't due to some kind of TLS interception with an invalid certificate?

What does ssllabs say? https://www.ssllabs.com/ssltest/analyze.html?d=netboot.geekery.cn&latest

iPXE CA is unlikely to do anything that diverges from Mozilla, if it is missing there (unlikely) then it is there it needs to be added.

Opening multiple issues about the same actuall issue is wasting resources. even if well intended.

**Comment by Paper-Dragon** [comment]
Have you solved it?
