### ISSUE TITLE
scriptlet works for undionly.kpxe but not snponly.efi

### ISSUE THREAD

**Issue by tbsky** [ipxe/ipxe#184]
Hi:
   just use the latest v1.20.1.tar.gz for testing.
   legacy boot with undionly.kpxe and scriptlet works fine.
   uefi boot with snponly.efi and scriptlet is not working. but when I type "config" to check configuration, I can see the correct scriptlet parameters is received from dhcp server,  it just didn't get executed.
   could it be fixed so scriptlet can work both for legacy bios and uefi?

**Comment by mcb30** [comment]
The `${scriptlet}` setting exists as an alternative to embedded images.  It can be used to override the default automatic boot process (of performing DHCP and booting whatever filename is returned via DHCP).

It was intended to be used via a settings mechanism that exists before iPXE performs DHCP, such as VMware GuestInfo or in non-volatile storage in a network card EEPROM.  It was never intended to be provided as a DHCP option.

However, in the case of `undionly.kpxe`, the DHCP options obtained by the original PXE ROM are available to iPXE before iPXE makes its own DHCP request.  The `${scriptlet}` setting is therefore working for you in this setup by accident, rather than by design.

I would probably recommend that you redesign your workflow to avoid the use of `${scriptlet}`, since you are currently using it in a way that was never intended to work and may break in future.  However, if you do want to continue to use `${scriptlet}` then issue #188 would make it work for you with `snponly.efi`.

Thanks
