### ISSUE TITLE
Error using EFI IPXE with exit 1 

### ISSUE THREAD

**Issue by FrancoCapraro** [ipxe/ipxe#601]
Hello I'm using EFI IPXE pendrive done with 21 version of IPXE.
I have 2 pendrives connect to my computer. one has ipxe uefi(1st in boot list) and another has windows 10 uefi (2nd in boot list). 
I do a simple script in IPXE doing a "exit 1" to boot from second pendrive. 
`#!ipxe`
`show platform`
`echo 7:59am`
`sleep 1`
`ifopen net0`
`shell`

![image](https://user-images.githubusercontent.com/37583249/155720215-9b94d741-96a1-4133-b990-7f2c15aa9252.png)
I saw that : 
class:300000 == EFI_SOFTWARE
subclass: 50000 == EFI_SOFTWARE_DXE_BS_DRIVER
operation:  D == EFI_SW_EC_CFG_DEFAULT

I use the same code and scene in an older computer and it works, window installer start. This test it's useless, my main idea is to do a sanbook iscsi with a VHD stored in the Server computer, but im having a lot of problem so i start with basic tests.

My IPXE working in Legacy mode is:

`#!ipxe`
`show platform`
`retry:`
`ifopen net0 || goto retry`
`set net0/netmask 255.255.255.0`
`set net0/gateway 172.20.0.12`
`set net0/ip 172.20.0.14`
`set net0/keep-san 1`
`echo Requesting image LEFT`
`sanboot iscsi:172.20.0.12::::OIT_LEFT || goto retry`

Best,
FC

**Comment by NiKiZe** [comment]
iPXE is here an efi application, with `exit 1` you make iPXE exit with return code 1.
How this is handled in the EFI firmware is up to the efi firmware implementors, we are just hoping that they implement it as "use next boot device"

Unfortunately there is nothing iPXE can do about the EFI firmware implementation, you have to contact the EFI vendor or hardware vendor to get a real fix in place. (Since there is nothing wrong with iPXE here, and nothing that can be done I will be closing this issue)

There might be workarounds, such as discussed in #447

In regards to your scripts, note that you do **sanboot** on legacy - this works in efi as well, just make sure that you have a valid image for EFI boot.
