### ISSUE TITLE
Connection timed out 4c1b2092

### ISSUE THREAD

**Issue by mc3001** [ipxe/ipxe#885]
I am able to get a DHCP address but can't reach anything after.
![image](https://user-images.githubusercontent.com/124831366/217646477-d5519656-e336-477d-b119-c75571ba4aa3.png)

Can't ping anything either

**Comment by mcb30** [comment]
Did you try looking at the URL that the error message helpfully provides to you?

https://ipxe.org/4c116092

**Comment by mc3001** [comment]
my dns is ok. 
I just can't reach anything

**Comment by mc3001** [comment]
![image](https://user-images.githubusercontent.com/124831366/217665569-894b0492-87ac-4ebb-b9bd-63757d0a06d6.png)

**Comment by NiKiZe** [comment]
Can you tcpdump the connection and check if DNS requests are made, and where to.

iPXE is clear on that DNS requests is timing out. Now you need to find why. Incorrect server address, routing or firewall issues, hardware issues, or iPXE software issues.

Do you have any other machine where it works? Have you tried a virtual machine so that you can dump the traffic?

**Comment by mcb30** [comment]
> my dns is ok. I just can't reach anything

Your DNS is not OK.  The only possible way to see the error https://ipxe.org/4c116092 is if iPXE fails to get a response from your DNS server.  Please don't assume that you know more than the people trying to help you.

**Comment by mc3001** [comment]
I'm just saying that I can't even ping anything around me or even its gateway via ip address, so DNS is not the issue here. As I mentioned I am able to get DHCP and the DNS address is set correctly:
![image](https://user-images.githubusercontent.com/124831366/218208521-1fec0f44-8cf8-4e97-bc5b-031dc8b9e6f7.png)

This issue is specific to these HP Zcentral 4R WS machines. We have other computers that can see the network just fine through ipxe on the same network. I know that this may be a driver issue. We added the drivers in before compiling the snponly.efi

**Comment by NiKiZe** [comment]
You might have to really check the traffic here with tcpdump or similar to see what is going on.

Is the requests going out correctly? Are they coming back? What about http requests on IP instead?

**Comment by mcb30** [comment]
> I'm just saying that I can't even ping anything around me or even its gateway via ip address, so DNS is not the issue here.

So far you have shown us only a single error message relating to a connection attempt, and that error was a DNS timeout (https://ipxe.org/4c116092).  It's entirely possible that your problem may turn out to be lower in the stack.  But please try actually showing us the problem, instead of just telling us your interpretation of what you think the problem might be.

Try, for example, showing us the errors that you get when trying to ping something by IP address.

The output from the `route` command would also be useful to see.

**Comment by mc3001** [comment]
![image](https://user-images.githubusercontent.com/124831366/218214874-be3d0fd8-1003-474f-9b7a-f5ca9954d8f1.png)

**Comment by mc3001** [comment]
![image](https://user-images.githubusercontent.com/124831366/218216124-16e69da2-bff9-4a2b-86fc-5ec9a5f73a08.png)

**Comment by NiKiZe** [comment]
What is the IP of the DHCP server? And are you using and DHCP relay agent on switch or similar?

**Comment by mc3001** [comment]
the dncp/dns is on the image on the post before where I tried to ping it and it timed out

**Comment by NiKiZe** [comment]
That is your gateway, which might be the same, but that is not clear. And you did not answer the questions.

We want to help you, but you need to answer the questions. And stop ignoring half of it.

**Comment by mc3001** [comment]
the first part is the dns/dhcp 
![image](https://user-images.githubusercontent.com/124831366/218227502-c2d80be0-08bd-4c64-8dd3-f2ca95e43269.png)

the second one is the gateway 
![image](https://user-images.githubusercontent.com/124831366/218227534-5b2d59e2-dea3-429b-85d9-1b6e79360993.png)

there is a dhcp helper address on the router but no dhcp relay agent on a switch

**Comment by NiKiZe** [comment]
In that case you are back to tcpdump/wireshark

**Comment by NiKiZe** [comment]
I'm closing this as no follow up was provided, feel free to share any tcpdump showing that the DNS requests are coming thru, but not used by iPXE and we are happy to reopen.
