### ISSUE TITLE
Could not open net0: Input/output error (https://ipxe.org/1d6a4698)

### ISSUE THREAD

**Issue by antermin** [ipxe/ipxe#991]
On a no-brand mini computer (Celeron N3050, 2x RTL8111 series Gigabit port), I am running into `1d6a4698` error using 1.21.1 (self-compiled) and `netboot.xyz` UEFI binary.

The PC is able to fetch iPXE via local network (server serves iPXE through pixiecore), and then after a while, the `1d6a4698` error appears for 0.5s and the screen goes blank.

I have tried adding `DEBUG=nii` but it still prints no debug message.

Apparently there is also a similar situation described [here](https://www.itninja.com/question/uefi-ipxe-booting-new-dell-optiplex-7460-to-k2000), the user ran into the same error using Optiplex 7460.

**Comment by NiKiZe** [comment]
I assume you are booting snponly.efi or snp.efi, since you seem to be using the NII interface.
When this is the case iPXE can't do much about broken firmware implementations.

What I recommend you to do is to try ipxe.efi instead, which should have native drivers for your nic.

Other than that try firmware update, if that don't help reach out to the hardware manufacturer. Or maybe even try and unload the Realtek driver and start the latest one from their homepage.

It is unlikely that anyone in the project will have resources to help you debug this issue further.
To make the link clickable, here is the error URL https://ipxe.org/1d6a4698

**Comment by mcb30** [comment]
> I have tried adding `DEBUG=nii` but it still prints no debug message.

Every possible code path that produces the error https://ipxe.org/1d6a4698 will first print a debug message if `DEBUG=nii` is enabled, and the debug message will appear before the "Could not open net0" message that you describe seeing.

Please retry with `DEBUG=nii` and post a screenshot showing the error message.
